name: CI

on:
  pull_request:
    paths:
      - '**/*.md'  
    branches:
      - main

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  

    - name: Install Markdown linting dependencies
      run: |
        npm install -g markdownlint-cli markdownlint-rule-quick-link

    - name: Run markdown lint
      run: |
        markdownlint '**/*.md' --fix
        markdownlint --version

  spellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install spell check dependencies
      run: |
        npm install -g cspell
        cspell --version

    - name: Run spell check
      run: |
        cspell '**/*.md'
